# Generated by Django 4.2.16 on 2024-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('residence', models.CharField(max_length=255)),
                ('parent_info', models.TextField()),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
